// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJDF-Ss3V5G_CZHqEmVcvEVA3aVEd_Qbo',
    appId: '1:946923857460:oliviaa:0afe8a217d2ec1b79f0c61',
    messagingSenderId: '946923857460',
    projectId: 'testnewtemp-85c9c',
    authDomain: 'testnewtemp-85c9c.firebaseapp.com',
    storageBucket: 'testnewtemp-85c9c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUxixFNxLe_L46v1vWS0JghqjiFtjviAA',
    appId: '1:946923857460:android:cb1bd2c294aa274f9f0c61',
    messagingSenderId: '946923857460',
    projectId: 'testnewtemp-85c9c',
    storageBucket: 'testnewtemp-85c9c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDouYm3rWu_7lzSnul9xRlNFWPEkoCcb3o',
    appId: '1:946923857460:ios:41ad9dfe6b895fe79f0c61',
    messagingSenderId: '946923857460',
    projectId: 'testnewtemp-85c9c',
    storageBucket: 'testnewtemp-85c9c.firebasestorage.app',
    iosBundleId: 'com.trujena.olivia',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDouYm3rWu_7lzSnul9xRlNFWPEkoCcb3o',
    appId: '1:946923857460:ios:41ad9dfe6b895fe79f0c61',
    messagingSenderId: '946923857460',
    projectId: 'testnewtemp-85c9c',
    storageBucket: 'testnewtemp-85c9c.firebasestorage.app',
    iosBundleId: 'com.trujena.olivia',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAJDF-Ss3V5G_CZHqEmVcvEVA3aVEd_Qbo',
    appId: '1:946923857460:oliviaa:30970cdc4c32ff419f0c61',
    messagingSenderId: '946923857460',
    projectId: 'testnewtemp-85c9c',
    authDomain: 'testnewtemp-85c9c.firebaseapp.com',
    storageBucket: 'testnewtemp-85c9c.firebasestorage.app',
  );
}
